import crypto from "node:crypto";
import type { Request, RequestHandler, Response } from "express";
import { pool } from "./db.ts";
import { extractToken, verifyToken } from "./auth.ts";
import { isUnsafeMethod } from "./rate-limit.ts";

/**
 * Minimum length an `Idempotency-Key` header value may have.
 *
 * Keys are generated by the offline mutation queue as 128-bit UUID-shaped
 * strings, so anything shorter than this is a client bug rather than a key,
 * and accepting it would let a truncated or hand-typed value collide with a
 * future real key.
 */
export const IDEMPOTENCY_KEY_MIN_LENGTH = 8;

/**
 * Maximum length an `Idempotency-Key` header value may have.
 *
 * Bounds the stored key so a hostile client cannot stuff multi-kilobyte
 * strings into the unique index; real keys are 36-character UUID strings.
 */
export const IDEMPOTENCY_KEY_MAX_LENGTH = 200;

/**
 * How long a duplicate waits for the in-flight original to settle, in
 * milliseconds, before answering 409. Override: `PM_WEB_IDEMPOTENCY_WAIT_MS`.
 *
 * The default covers the longest mutating route (pm CLI commands time out at
 * 30 s), so a concurrent duplicate normally observes the original's stored
 * outcome instead of being told to retry.
 */
const DEFAULT_WAIT_MS = 30_000;

/** How often a waiting duplicate re-checks the store, in milliseconds. */
const DEFAULT_POLL_MS = 25;

/** Age after which an unfinished execution is reported as outcome unknown. */
const DEFAULT_PENDING_TIMEOUT_MS = 300_000;

/**
 * How long a settled idempotency record is kept before it is swept, in
 * milliseconds. Override: `PM_WEB_IDEMPOTENCY_RETENTION_MS`.
 *
 * Completed outcomes are deduplicated within this window. A retry after expiry
 * can execute again. Unknown outcomes have the same bounded retention, measured
 * from settlement; stale pending intents must settle before they can expire.
 */
const DEFAULT_RETENTION_MS = 7 * 24 * 60 * 60 * 1000;

/**
 * One stored idempotency record, as the `pm_idempotency_keys` table holds it.
 *
 * `status_code` is `null` while the execution that owns the key is still in
 * flight (or crashed before responding); every other field is immutable once
 * written, which is what makes a replayed outcome trustworthy.
 */
interface IdempotencyRecord {
  /** Row id of the record, used to target the outcome update. */
  id: string;
  /** Fingerprint of the request the key was created for. */
  request_fingerprint: string;
  /** Response status once settled; `null` while pending. */
  status_code: number | null;
  /** Serialized response body once settled; `null` when the response had none. */
  response_body: string | null;
  /** Content type the settled response carried; `null` when unknown. */
  response_content_type: string | null;
  /** When the intent was inserted; drives the unknown-outcome deadline. */
  created_at: Date;
  /** Explicit terminal ambiguity is never automatically re-executed. */
  outcome_state: 'pending' | 'completed' | 'outcome_unknown';
}

/** Handler assertions are process-local and cannot be forged through request headers. */
const preCommitFailures = new WeakSet<Response>();

/** Mark a failure only after proving no mutation committed (for example, confirmed rollback before COMMIT was attempted). */
export function markIdempotencyPreCommitFailure(res: Response): void {
  preCommitFailures.add(res);
}

/** Machine-readable refusal reused by failure settlement and stale-intent recovery. */
const UNKNOWN_OUTCOME = JSON.stringify({
  code: "PM_IDEMPOTENCY_OUTCOME_UNKNOWN",
  error: "Idempotency outcome unknown; reconcile the original mutation before submitting new work",
});

/**
 * Compute the fingerprint that binds one idempotency key to one request.
 *
 * The fingerprint covers the method, the full path with query string, and the
 * parsed JSON body, so a key can only ever be replayed for the identical
 * request it was created for. Re-serializing the parsed body is stable here
 * because a retry sends the same bytes (the offline queue persists the exact
 * body string), which parses to the same property order; a different body —
 * different properties or different values — produces a different fingerprint
 * and is rejected rather than silently deduplicated.
 *
 * @param method - The HTTP method of the request.
 * @param path - The request path including any query string.
 * @param body - The parsed request body, or `null` when the request has none.
 * @returns A hex SHA-256 digest over the request identity.
 */
export function requestFingerprint(method: string, path: string, body: unknown): string {
  return crypto
    .createHash("sha256")
    .update(`${method}\n${path}\n${JSON.stringify(body ?? null)}`)
    .digest("hex");
}

/**
 * Resolve a positive millisecond duration from the environment.
 *
 * Accepts only finite positive numbers; anything else (unset, empty, zero,
 * negative, non-numeric) falls back to the shipped default so a typo in an
 * environment variable degrades to the documented behaviour instead of
 * disabling a timeout entirely.
 *
 * @param name - The environment variable to read.
 * @param fallback - The default used when the variable is unusable.
 * @returns The resolved duration in milliseconds.
 */
function envDurationMs(name: string, fallback: number): number {
  const parsed = Number(process.env[name]);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

/**
 * Insert the intent to execute one keyed request, or report a conflict.
 *
 * `ON CONFLICT DO NOTHING` makes the insert atomic against a concurrent
 * duplicate: exactly one request can own a (user, key) pair at a time, and
 * the loser learns it lost by receiving no row rather than by an error it
 * would have to disambiguate from a genuine failure.
 *
 * @returns The id of the inserted row when this call owns the execution, or
 *   `null` when the key is already held.
 */
async function insertPendingKey(
  userId: string,
  key: string,
  method: string,
  path: string,
  fingerprint: string,
): Promise<string | null> {
  const result = await pool.query<{ id: string }>(
    `INSERT INTO pm_idempotency_keys (user_id, idempotency_key, method, path, request_fingerprint)
     SELECT id, $2, $3, $4, $5 FROM pm_users WHERE id = $1 FOR KEY SHARE
     ON CONFLICT (user_id, idempotency_key) DO NOTHING
     RETURNING id`,
    [userId, key, method, path, fingerprint],
  );
  const row = result.rows[0] as { id: string } | undefined;
  return row?.id ?? null;
}

/** Check that a verified token still names an existing account before keying. */
async function accountExists(userId: string): Promise<boolean> {
  if (typeof userId !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(userId)) return false;
  const result = await pool.query("SELECT id FROM pm_users WHERE id = $1", [userId]);
  return result.rows.length > 0;
}

/**
 * Read the current idempotency record for one (account, key) pair.
 *
 * @returns The record, or `null` when no row exists (which can only happen
 *   transiently: a settled record is swept only by retention, and a pending
 *   one only by an explicit transient refusal).
 */
async function selectKey(userId: string, key: string): Promise<IdempotencyRecord | null> {
  const result = await pool.query<IdempotencyRecord>(
    `SELECT id, request_fingerprint, status_code, response_body, response_content_type, created_at, outcome_state
     FROM pm_idempotency_keys
     WHERE user_id = $1 AND idempotency_key = $2`,
    [userId, key],
  );
  return (result.rows[0] as IdempotencyRecord | undefined) ?? null;
}

/**
 * Sweep idempotency records past the retention window.
 *
 * Called at most once per minute per guard instance. Stale pending records first
 * become terminal unknown outcomes; retention starts at that settlement time.
 */
async function deleteExpiredKeys(): Promise<void> {
  await pool.query(
    `UPDATE pm_idempotency_keys SET outcome_state = 'outcome_unknown', status_code = 409,
     response_body = $2, response_content_type = 'application/json', updated_at = NOW()
     WHERE status_code IS NULL AND outcome_state = 'pending'
     AND created_at < NOW() - ($1::double precision * interval '1 ms')`,
    [envDurationMs("PM_WEB_IDEMPOTENCY_PENDING_TIMEOUT_MS", DEFAULT_PENDING_TIMEOUT_MS), UNKNOWN_OUTCOME],
  );
  await pool.query(
    `DELETE FROM pm_idempotency_keys
     WHERE status_code IS NOT NULL AND updated_at < NOW() - ($1::double precision * interval '1 ms')`,
    [envDurationMs("PM_WEB_IDEMPOTENCY_RETENTION_MS", DEFAULT_RETENTION_MS)],
  );
}

/**
 * Store a definitive outcome. Release only explicit pre-mutation refusals
 * (425, 429, or handler-proven pre-commit failures). All other server failures
 * settle as terminal unknown outcomes because they may follow a commit.
 */
async function persistOutcome(
  rowId: string,
  statusCode: number,
  body: string | null,
  contentType: string | null,
  preCommit = false,
): Promise<void> {
  if (statusCode === 425 || statusCode === 429 || (statusCode >= 500 && preCommit)) {
    await pool.query(`DELETE FROM pm_idempotency_keys WHERE id = $1 AND outcome_state = 'pending'`, [rowId]);
    return;
  }
  const unknown = statusCode >= 500;
  await pool.query(
    `UPDATE pm_idempotency_keys
     SET status_code = $2, response_body = $3, response_content_type = $4, outcome_state = $5, updated_at = NOW()
     WHERE id = $1 AND outcome_state = 'pending'`,
    [rowId, unknown ? 409 : statusCode, unknown ? UNKNOWN_OUTCOME : body,
      unknown ? "application/json" : contentType, unknown ? "outcome_unknown" : "completed"],
  );
}

/**
 * Answer a duplicate from the stored outcome of the original request.
 *
 * The `Idempotency-Replayed` header lets the client (and the tests) tell a
 * replay from a fresh execution without diffing bodies. Responses that had no
 * body keep having none; responses that had one are served with the content
 * type they originally carried.
 */
function replayStored(record: IdempotencyRecord, res: Response): void {
  res.setHeader("Idempotency-Replayed", "true");
  if (record.response_body === null) {
    res.status(record.status_code ?? 500).end();
    return;
  }
  res.setHeader("Content-Type", record.response_content_type ?? "application/json");
  res.status(record.status_code ?? 500).send(record.response_body);
}

/**
 * Answer a settled record, or reject a key recycled onto a different request.
 *
 * @param record - The settled record held under the client's key.
 * @param fingerprint - The fingerprint of the request being answered.
 * @param res - The response to answer on.
 */
function finishSettled(record: IdempotencyRecord, fingerprint: string, res: Response): void {
  if (record.request_fingerprint !== fingerprint) {
    res.status(422).json({
      error: "Idempotency-Key was already used for a different request",
    });
    return;
  }
  replayStored(record, res);
}

/**
 * Capture the executing request's response and persist it when it finishes.
 *
 * `res.json`/`res.send` are wrapped once to record the body the handler
 * produced, and the `finish` listener persists whatever status the response
 * left with — so handlers that never call `json`/`send` (204s, `end()`) are
 * still memoized, just without a body.
 *
 * @param rowId - The id of this execution's idempotency record.
 * @param res - The executing response.
 */
function captureOutcome(rowId: string, res: Response): void {
  let capturedBody: string | null = null;
  const originalJson = res.json.bind(res);
  const originalSend = res.send.bind(res);
  /** Capture the first response serialization without recording request content. */
  const capture = (body: unknown): void => {
    if (capturedBody !== null) return;
    capturedBody = typeof body === "string" ? body : JSON.stringify(body ?? null);
  };
  res.json = (body?: unknown): Response => {
    capture(body);
    return originalJson(body);
  };
  res.send = (body?: unknown): Response => {
    capture(body);
    return originalSend(body);
  };
  let finished = false;
  /** Finish and premature close share one persistence path, avoiding conflicting writes. */
  const settle = (statusCode: number): void => {
    const contentType = res.getHeader("Content-Type");
    void persistOutcome(
      rowId,
      statusCode,
      capturedBody,
      typeof contentType === "string" ? contentType : null,
      preCommitFailures.has(res),
    ).catch((error: unknown) => {
      // Do not log response bodies, tokens or database error details.
      console.error("Failed to persist idempotency outcome; key remains pending", error instanceof Error ? error.name : "unknown error");
    });
  };
  res.on("finish", () => {
    finished = true;
    settle(res.statusCode);
  });
  res.on("close", () => {
    if (!finished) settle(500);
  });
}

/**
 * Build the middleware that makes keyed mutating requests at-most-once.
 *
 * Scope: keyed mutating `/api` requests outside `/api/auth`. Auth responses
 * always execute live so session cookies are never lost to body-only replay.
 * An expected-account header is checked against an existing authenticated user
 * before execution or claiming, including recovery probes to `/api/auth/me`.
 *
 * Exactly-once per account: the key is stored together with the authenticated
 * user, so two accounts using the same key never interfere. The first
 * execution atomically claims the (account, key) pair, stores its outcome
 * when the response finishes, and any duplicate — a retry after an ambiguous
 * response the client never saw, or a concurrent duplicate of an in-flight
 * request — is answered from that stored outcome without re-executing. A key
 * reused for a *different* request is rejected with 422 rather than silently
 * deduplicated; an unfinished record older than the pending timeout is
 * answered with 409 outcome unknown without re-execution; an in-flight
 * duplicate waits for it to settle and answers 409 only at the
 * deadline.
 *
 * @returns An Express middleware enforcing the contract on its mount.
 */
export function idempotencyGuard(): RequestHandler {
  let nextSweepAt = 0;
  return async (req: Request, res: Response, next) => {
    const authRoute = /^\/api\/auth(?:\/|$)/i.test(req.originalUrl.split("?")[0]);
    const expectedAccount = req.get("x-pm-expected-account");
    const checkExpected = expectedAccount !== undefined
      && (!authRoute || /^\/api\/auth\/me\/?(?:\?|$)/i.test(req.originalUrl));
    const header = req.get("idempotency-key");
    const keyed = isUnsafeMethod(req.method) && !authRoute && header !== undefined;
    if (!keyed && !checkExpected) {
      next();
      return;
    }
    // Only record requests we can attribute to an account; an unauthenticated
    // or invalid-session request is passed through for the route to refuse,
    // so an anonymous probe can never occupy a key.
    let userId: string | null = null;
    const token = extractToken(req);
    if (token) {
      try {
        userId = verifyToken(token).userId;
      } catch {
        userId = null;
      }
    }
    if (userId !== null && !await accountExists(userId)) userId = null;
    if (checkExpected && (userId === null || expectedAccount !== userId)) {
      res.status(409).json({ code: "PM_EXPECTED_ACCOUNT_MISMATCH", error: "The signed-in account differs from the account that approved this work" });
      return;
    }
    if (!keyed || userId === null) {
      next();
      return;
    }
    const key = header!.trim();
    if (key.length < IDEMPOTENCY_KEY_MIN_LENGTH || key.length > IDEMPOTENCY_KEY_MAX_LENGTH) {
      res.status(400).json({
        error: `Idempotency-Key must be between ${IDEMPOTENCY_KEY_MIN_LENGTH} and ${IDEMPOTENCY_KEY_MAX_LENGTH} characters`,
      });
      return;
    }

    if (Date.now() >= nextSweepAt) {
      // Cleanup can fail only before an intent exists, leaving the key retryable.
      nextSweepAt = Date.now() + 60_000;
      await deleteExpiredKeys();
    }

    const fingerprint = requestFingerprint(req.method, req.originalUrl, req.body);
    const deadline = Date.now() + envDurationMs("PM_WEB_IDEMPOTENCY_WAIT_MS", DEFAULT_WAIT_MS);
    let rowId = await insertPendingKey(userId, key, req.method, req.originalUrl, fingerprint);
    while (rowId === null) {
      const record = await selectKey(userId, key);
      if (record && record.status_code !== null) {
        // The original settled before this duplicate arrived: replay it.
        finishSettled(record, fingerprint, res);
        return;
      }
      if (record && record.request_fingerprint !== fingerprint) {
        res.status(422).json({
          error: "Idempotency-Key was already used for a different request",
        });
        return;
      }
      if (record === null) {
        // Deletion can race token validation; the locked INSERT SELECT refuses
        // a missing user without a foreign-key failure or a permanent wait.
        if (!await accountExists(userId)) {
          next();
          return;
        }
        rowId = await insertPendingKey(userId, key, req.method, req.originalUrl, fingerprint);
        continue;
      }
      if (isStalePending(record)) {
        await persistOutcome(record.id, 500, null, null);
        continue;
      }
      if (Date.now() >= deadline) {
        res.status(409).json({ code: "PM_IDEMPOTENCY_IN_FLIGHT", error: "The request with this Idempotency-Key is still executing; retry later" });
        return;
      }
      await new Promise((resolve) => { setTimeout(resolve, envDurationMs("PM_WEB_IDEMPOTENCY_POLL_MS", DEFAULT_POLL_MS)); });
    }

    captureOutcome(rowId, res);
    next();
  };
}

/**
 * Report whether a pending record is old enough to be a crashed execution.
 *
 * @param record - The still-pending record to age-check.
 * @returns `true` when the record predates the pending timeout.
 */
function isStalePending(record: IdempotencyRecord): boolean {
  const timeoutMs = envDurationMs(
    "PM_WEB_IDEMPOTENCY_PENDING_TIMEOUT_MS",
    DEFAULT_PENDING_TIMEOUT_MS,
  );
  return Date.now() - record.created_at.getTime() > timeoutMs;
}
